<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مشکل مسکن
</font>
</h1>

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مقدمه و صورت مسئله
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
در این سوال ما به دنبال آموزش یک مدل یادگیری ماشین هستیم که بتوان با کمک آن قیمت مسکن در کشور پهناور ایران را پیش‌بینی کنیم. با استفاده از مجموعه داده‌ای که در اختیار شما قرار گرفته است، به ایجاد و تخمین متغیری به نام <code>Total</code> می‌پردازیم. این متغیر در مجموعه‌داده‌ ما وجود ندارد. در ادامه به نحوه ایجاد و محاسبه‌ی آن پرداخته می‌شود.
</font>
</p>

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معرفی مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
در فایل اولیه‌ی این سوال، یک پوشه با نام <code>Data</code> وجود دارد که شامل ۲ فایل <code>train.csv</code> و <code>test.csv</code> وجود دارد. در این بخش به بررسی این ۲ فایل می‌پردازیم.
</font>
</p>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
هرستون این مجموعه‌داده با توجه به ماهیت خود می‌تواند مقادیر عددی یا رشته‌ای داشته باشند. برای آشنایی بیشتر با مجموعه‌داده، پیشنهاد می‌شود هرستون به صورت جداگانه بررسی شود.</font>
</p>

<h4 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معرفی مجموعه داده آموزشی (train.csv)
</font>
</h4>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
فایل <code>train.csv</code> دارای ۲۰ ستون می‌باشد که ستون‌های آن به شرح زیر می‌باشد:
<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|<code>Area</code>|متراژ خانه‌های به متر مربع|
|<code>Year_built</code>|سال ساخت ساختمان|
|<code>Rooms</code>|تعداد اتاق‌ها|
|<code>Floor</code>|شماره‌ی طبقه‌ی واحد در خانه|
|<code>Elevator</code>|وجود آسانسور|
|<code>Parking</code>|وجود پارکینگ|
|<code>StorageRoom</code>|وجود انباری|
|<code>Rent_type</code>|نوع اجاره‌ی خانه|
|<code>Units_per_floor</code>|تعداد واحد در هر طبقه|
|<code>Building_direction</code>|جهت جغرافیایی ساختمان|
|<code>Unit_status</code>|وضعیت بازسازی واحد|
|<code>Floor_material</code>|جنس کف‌پوش|
|<code>Bathroom</code>|نوع دستشویی واحد|
|<code>Balcony</code>|وجود بالکن|
|<code>Heating</code>|نوع گرمایش|
|<code>Cooling</code>|نوع سرمایش|
|<code>Hot_water_provider</code>|نوع گرم‌کن آب|
|<code>District</code>|منطقه جغرافیایی در شهر|
|<code>City</code>|شهری که واحد مسکونی در آن واقع شده|
|<code>Credit</code>|میزان پول پیش برای اجاره‌ی واحد (میلیون تومان)|
|<code>Rent</code>|میزان اجاره واحد (میلیون تومان)|

</font>
</div>
</center>

<h4 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معرفی مجموعه داده آزمون (test.csv)
</font>
</h4>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
فایل <code>test.csv</code> دارای ۱۹ ستون می‌باشد که ستون‌های آن به شرح زیر می‌باشد:


<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|<code>Area</code>|متراژ خانه‌های به متر مربع|
|<code>Year_built</code>|سال ساخت ساختمان|
|<code>Rooms</code>|تعداد اتاق‌ها|
|<code>Floor</code>|شماره‌ی طبقه‌ی واحد در خانه|
|<code>Elevator</code>|وجود آسانسور|
|<code>Parking</code>|وجود پارکینگ|
|<code>StorageRoom</code>|وجود انباری|
|<code>Rent_type</code>|نوع اجاره‌ی خانه|
|<code>Units_per_floor</code>|تعداد واحد در هر طبقه|
|<code>Building_direction</code>|جهت جغرافیایی ساختمان|
|<code>Unit_status</code>|وضعیت بازسازی واحد|
|<code>Floor_material</code>|جنس کف‌پوش|
|<code>Bathroom</code>|نوع دستشویی واحد|
|<code>Balcony</code>|وجود بالکن|
|<code>Heating</code>|نوع گرمایش|
|<code>Cooling</code>|نوع سرمایش|
|<code>Hot_water_provider</code>|نوع گرم‌کن آب|
|<code>District</code>|منطقه جغرافیایی در شهر|
|<code>City</code>|شهری که واحد مسکونی در آن واقع شده|

</font>
</div>
</center>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
در این قسمت کتاب‌خانه‌ها و ابزار مورد نیاز خود را <code>import</code> کنید و فایل داده‌ها را که در پوشه‌ی <code>Data</code> و که با نام‌های <code>train.csv</code> و <code>test.csv</code> ذخیره‌شده‌اند را بخوانید و وارد محیط کار خود کنید.
</font>
</p>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [94]:
import pandas as pd

train_file_path = '/content/drive/MyDrive/Colab Notebooks/FinAI/5_housing/Data/train.csv'
test_file_path = '/content/drive/MyDrive/Colab Notebooks/FinAI/5_housing/Data/test.csv'

try:
    # Load training data
    print("="*80)
    train_df = pd.read_csv(train_file_path)
    print(f"Training data loaded successfully. Dimensions: {train_df.shape}")
    print("First five rows of training data:")
    print(train_df.head())

    # Load test data
    print("="*80)
    test_df = pd.read_csv(test_file_path)
    print(f"\nTest data loaded successfully. Dimensions: {test_df.shape}")
    print("First five rows of test data:")
    print(test_df.head())

except FileNotFoundError:
    print(f"Error: Files '{train_file_path}' or '{test_file_path}' not found.")
    print("Please ensure the data files are in the specified path and check file names.")
    print("If file names are different, update the 'train_file_path' and 'test_file_path' variables.")
except Exception as e:
    print(f"An error occurred while loading the data: {e}")

================================================================================
Training data loaded successfully. Dimensions: (478084, 21)
First five rows of training data:
    Area Year_built Rooms   Floor  Elevator  Parking  StorageRoom  \
0  100.0       1398     1    همکف       0.0      0.0          0.0
1   92.0       1391     2  5 از 5       1.0      0.0          1.0
2   77.0       1403     2       2       1.0      1.0          0.0
3  120.0       1388     2       2       0.0      0.0          1.0
4  145.0       1403     3  4 از 6       1.0      1.0          1.0

        Rent_type Units_per_floor Building_direction  ... Floor_material  \
0  غیر قابل تبدیل     انتخاب نشده        انتخاب نشده  ...    انتخاب نشده
1             NaN               2        انتخاب نشده  ...         سرامیک
2  غیر قابل تبدیل     انتخاب نشده        انتخاب نشده  ...    انتخاب نشده
3  غیر قابل تبدیل     انتخاب نشده        انتخاب نشده  ...    انتخاب نشده
4  غیر قابل تبدیل               4              جنوبی  ...         سرامیک

         Bathroom      Balcony      Heating      Cooling Hot_water_provider  \
0     انتخاب نشده  انتخاب نشده  انتخاب نشده  انتخاب نشده        انتخاب نشده
1  ایرانی و فرنگی         دارد        شوفاژ       اسپلیت               پکیج
2     انتخاب نشده  انتخاب نشده  انتخاب نشده  انتخاب نشده        انتخاب نشده
3     انتخاب نشده  انتخاب نشده  انتخاب نشده  انتخاب نشده        انتخاب نشده
4  ایرانی و فرنگی         دارد  داکت اسپلیت  داکت اسپلیت               پکیج

        District  Credit  Rent           city
0        unknown    50.0   5.0     shahrekord
1        unknown   400.0   0.0  bandar-anzali
2        unknown   450.0   0.1   shahin-shahr
3  vahid-isfahan    25.0   2.3        isfahan
4       golshahr  1200.0   0.0          karaj

[5 rows x 21 columns]
================================================================================

Test data loaded successfully. Dimensions: (144661, 19)
First five rows of test data:
    Area Year_built Rooms    Floor  Elevator  Parking  StorageRoom  \
0  195.0       1390     3   3 از 5       1.0      1.0          1.0
1   65.0       1388     2   4 از 5       1.0      0.0          1.0
2   45.0       1385     1   2 از 4       0.0      0.0          0.0
3   50.0       1402     1   1 از 3       1.0      0.0          0.0
4  105.0       1401     2  5 از 21       1.0      1.0          1.0

        Rent_type Units_per_floor Building_direction  Unit_status  \
0  غیر قابل تبدیل               2              شمالی  بازسازی شده
1             NaN     انتخاب نشده              جنوبی  بازسازی شده
2  غیر قابل تبدیل               1              جنوبی  بازسازی شده
3  غیر قابل تبدیل               3              شمالی  انتخاب نشده
4             NaN               6              جنوبی  انتخاب نشده

  Floor_material        Bathroom Balcony      Heating      Cooling  \
0         سرامیک  ایرانی و فرنگی    دارد  داکت اسپلیت  داکت اسپلیت
1         سرامیک  ایرانی و فرنگی    دارد        بخاری     کولر آبی
2         سرامیک          ایرانی    دارد        بخاری     کولر آبی
3      پارکت چوب           فرنگی   ندارد        شوفاژ    کولر گازی
4         سرامیک  ایرانی و فرنگی    دارد  داکت اسپلیت  داکت اسپلیت

  Hot_water_provider      District    city
0               پکیج   zafaraniyeh  tehran
1           آبگرم‌کن       jeyhoun  tehran
2           آبگرم‌کن      sarsabil  tehran
3               پکیج   zafaraniyeh  tehran
4               پکیج  chitgar-lake  tehran

In [72]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 478084 entries, 0 to 478083
Data columns (total 21 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Area                478056 non-null  float64
 1   Year_built          478056 non-null  object
 2   Rooms               478056 non-null  object
 3   Floor               478050 non-null  object
 4   Elevator            478050 non-null  float64
 5   Parking             478054 non-null  float64
 6   StorageRoom         478054 non-null  float64
 7   Rent_type           381573 non-null  object
 8   Units_per_floor     478084 non-null  object
 9   Building_direction  478084 non-null  object
 10  Unit_status         478084 non-null  object
 11  Floor_material      478084 non-null  object
 12  Bathroom            478084 non-null  object
 13  Balcony             478084 non-null  object
 14  Heating             478084 non-null  object
 15  Cooling             478084 non-null  object
 16  Hot_water_provider  478084 non-null  object
 17  District            478084 non-null  object
 18  Credit              478084 non-null  float64
 19  Rent                478084 non-null  float64
 20  city                478084 non-null  object
dtypes: float64(6), object(15)
memory usage: 76.6+ MB

In [30]:
train_df.isna().sum()

Area                     28
Year_built               28
Rooms                    28
Floor                    34
Elevator                 34
Parking                  30
StorageRoom              30
Rent_type             96511
Units_per_floor           0
Building_direction        0
Unit_status               0
Floor_material            0
Bathroom                  0
Balcony                   0
Heating                   0
Cooling                   0
Hot_water_provider        0
District                  0
Credit                    0
Rent                      0
city                      0
dtype: int64

In [22]:
print("\nnumercical of categorical data:")
train_df.describe(include="float")

numercical of categorical data:

,Area,Elevator,Parking,StorageRoom,Credit,Rent
count,4.780560e+05,478050.000000,478054.000000,478054.000000,4.780840e+05,4.780840e+05
mean,9.370845e+02,0.598002,0.724249,0.763485,1.059701e+04,1.108420e+04
std,5.542343e+04,0.490302,0.446893,0.424942,1.583288e+06,1.746685e+06
min,1.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00
25%,7.400000e+01,0.000000,0.000000,1.000000,1.500000e+02,1.000000e-01
50%,9.200000e+01,1.000000,1.000000,1.000000,3.000000e+02,3.000000e+00
75%,1.250000e+02,1.000000,1.000000,1.000000,6.000000e+02,1.000000e+01
max,1.000000e+07,1.000000,1.000000,1.000000,6.000000e+08,1.000000e+09

In [21]:
print("\ndescribe of categorical data:")
train_df.describe(include="object")

describe of categorical data:

,Year_built,Rooms,Floor,Rent_type,Units_per_floor,Building_direction,Unit_status,Floor_material,Bathroom,Balcony,Heating,Cooling,Hot_water_provider,District,city
count,478056,478056,478050,381573,478084,478084,478084,478084,478084,478084,478084,478084,478084,478084,478084
unique,34,6,615,2,10,5,3,8,4,3,8,6,4,1092,265
top,1390,2,1,غیر قابل تبدیل,انتخاب نشده,انتخاب نشده,انتخاب نشده,سرامیک,انتخاب نشده,دارد,انتخاب نشده,انتخاب نشده,انتخاب نشده,unknown,tehran
freq,42185,260993,52662,377898,219140,264773,226281,209454,201643,239813,223286,234169,218768,199981,146604

### check columns and values

In [105]:
floor_counts = train_df['Floor'].value_counts()
for idx, count in floor_counts.items():
    print(f"{idx}:\n\t {count}")

1:
	 52662
2:
	 51463
3:
	 39273
4:
	 23803
همکف:
	 22591
2 از 4:
	 18068
3 از 4:
	 17530
1 از 4:
	 16367
2 از 3:
	 15762
4 از 4:
	 15085
3 از 5:
	 14286
3 از 3:
	 13829
1 از 3:
	 13478
2 از 5:
	 13052
1 از 2:
	 12531
5:
	 12456
4 از 5:
	 12094
1 از 5:
	 11539
5 از 5:
	 10704
2 از 2:
	 9914
همکف از 2:
	 6260
همکف از 3:
	 5438
6:
	 4661
3 از 6:
	 4048
همکف از 4:
	 3702
5 از 6:
	 3661
4 از 6:
	 3532
2 از 6:
	 3523
زیرهمکف:
	 3156
1 از 6:
	 3082
6 از 6:
	 3059
7:
	 2328
8:
	 1322
همکف از 5:
	 1111
3 از 7:
	 957
5 از 7:
	 899
7 از 7:
	 888
6 از 7:
	 886
10:
	 886
زیرهمکف از 3:
	 882
4 از 7:
	 881
2 از 7:
	 824
9:
	 793
1 از 7:
	 763
زیرهمکف از 2:
	 728
4 از 8:
	 657
3 از 8:
	 621
2 از 8:
	 574
+30:
	 519
11:
	 514
1 از 8:
	 485
زیرهمکف از 4:
	 480
12:
	 473
6 از 8:
	 418
3 از 10:
	 410
7 از 8:
	 384
8 از 8:
	 367
5 از 8:
	 360
5 از 10:
	 359
2 از 10:
	 357
4 از 10:
	 353
1 از 10:
	 305
همکف از 6:
	 300
13:
	 292
3 از 9:
	 261
14:
	 257
3 از 2:
	 245
4 از 9:
	 242
7 از 10:
	 239
3 از 12:
	 218
7 از 9:
	 218
2 از 9:
	 215
8 از 10:
	 214
6 از 10:
	 196
5 از 9:
	 195
6 از 9:
	 191
2 از 12:
	 189
15:
	 188
1 از 9:
	 176
1 از 12:
	 174
4 از 12:
	 167
8 از 9:
	 165
10 از 10:
	 163
10 از 12:
	 160
6 از 12:
	 158
9 از 9:
	 157
9 از 10:
	 153
زیرهمکف از 5:
	 151
5 از 12:
	 145
14 از 14:
	 138
10 از 11:
	 133
9 از 12:
	 133
8 از 12:
	 128
5 از 4:
	 126
10 از 14:
	 123
7 از 11:
	 118
6 از 14:
	 115
11 از 14:
	 113
3 از 11:
	 112
4 از 11:
	 112
16:
	 109
1 از انتخاب نشده:
	 108
4 از 3:
	 108
2 از 14:
	 108
12 از 14:
	 107
7 از 12:
	 107
11 از 11:
	 106
3 از 14:
	 104
9 از 14:
	 103
4 از 14:
	 102
8 از 11:
	 102
20:
	 101
13 از 14:
	 100
9 از 11:
	 100
5 از 14:
	 100
4 از 2:
	 100
2 از 11:
	 98
همکف از 7:
	 94
1 از 11:
	 93
17:
	 92
5 از 11:
	 90
11 از 12:
	 90
8 از 14:
	 89
همکف از انتخاب نشده:
	 87
4 از 16:
	 86
12 از 12:
	 85
3 از 16:
	 81
3 از 15:
	 79
6 از 11:
	 78
2 از 16:
	 74
1 از 15:
	 74
4 از 15:
	 74
7 از 14:
	 74
1 از 14:
	 73
2 از 15:
	 73
همکف از 8:
	 71
18:
	 70
2 از 20:
	 69
3 از 20:
	 68
4 از 20:
	 67
5 از 15:
	 66
6 از 5:
	 62
8 از 15:
	 62
19:
	 61
1 از 16:
	 60
13 از 13:
	 59
همکف از 14:
	 56
12 از 15:
	 55
2 از انتخاب نشده:
	 54
5 از 2:
	 53
همکف از 10:
	 51
1 از 20:
	 51
30:
	 50
10 از 13:
	 50
1 از 13:
	 47
6 از 13:
	 46
7 از 15:
	 46
9 از 15:
	 45
10 از 15:
	 45
11 از 15:
	 44
7 از 13:
	 44
4 از 13:
	 44
13 از 15:
	 44
11 از 13:
	 44
6 از 15:
	 43
5 از 20:
	 42
14 از 15:
	 42
5 از 13:
	 41
3 از 13:
	 41
15 از 15:
	 40
23:
	 40
14 از 20:
	 38
23 از 25:
	 37
12 از 13:
	 36
همکف از 12:
	 36
5 از 3:
	 34
8 از 13:
	 34
25:
	 34
زیرهمکف از 6:
	 33
8 از 20:
	 33
10 از 20:
	 33
9 از 13:
	 32
25 از 25:
	 32
5 از 18:
	 32
15 از 20:
	 32
3 از 18:
	 32
10 از 25:
	 32
22:
	 31
21:
	 31
10 از 16:
	 30
همکف از 9:
	 29
11 از 20:
	 28
6 از 4:
	 28
13 از 20:
	 28
24:
	 26
3 از انتخاب نشده:
	 26
14 از 25:
	 26
18 از 25:
	 25
+30 از بیشتر از 30:
	 25
زیرهمکف از انتخاب نشده:
	 25
18 از 20:
	 25
12 از 20:
	 25
2 از 13:
	 24
20 از 25:
	 24
8 از 18:
	 23
4 از 24:
	 23
1 از 24:
	 23
همکف از 16:
	 22
12 از 18:
	 22
4 از 25:
	 22
14 از 16:
	 22
6 از 16:
	 21
10 از 18:
	 21
6 از 20:
	 21
9 از 16:
	 21
2 از 18:
	 20
2 از 24:
	 20
4 از انتخاب نشده:
	 20
16 از 20:
	 20
16 از 18:
	 20
7 از 18:
	 20
9 از 20:
	 20
19 از 20:
	 20
17 از 25:
	 20
5 از 24:
	 20
6 از 18:
	 20
4 از 18:
	 20
1 از 18:
	 19
7 از 16:
	 19
17 از 19:
	 19
15 از 21:
	 19
14 از 18:
	 19
3 از بیشتر از 30:
	 18
12 از 25:
	 18
6 از 2:
	 18
15 از 18:
	 18
3 از 24:
	 18
12 از 19:
	 18
28:
	 17
8 از 17:
	 17
همکف از 15:
	 17
6 از 17:
	 17
9 از 18:
	 17
5 از 30:
	 17
8 از 16:
	 17
6 از 24:
	 16
16 از 16:
	 16
8 از 25:
	 16
20 از 20:
	 16
12 از 17:
	 16
8 از 21:
	 16
1 از بیشتر از 30:
	 15
4 از 17:
	 15
1 از 25:
	 15
3 از 19:
	 15
5 از 16:
	 15
3 از 25:
	 15
9 از 25:
	 15
5 از 17:
	 15
16 از 25:
	 15
17 از 20:
	 15
24 از 25:
	 15
17 از 17:
	 14
7 از 6:
	 14
1 از 19:
	 14
12 از 21:
	 14
19 از 25:
	 14
13 از 17:
	 14
5 از 25:
	 14
10 از 17:
	 14
13 از 18:
	 14
21 از 25:
	 14
19 از 19:
	 14
14 از 17:
	 13
7 از 25:
	 13
همکف از 11:
	 13
9 از 17:
	 13
27:
	 13
4 از 22:
	 13
11 از 18:
	 13
12 از 16:
	 13
4 از 19:
	 13
15 از 25:
	 13
18 از 19:
	 12
6 از 19:
	 12
6 از 25:
	 12
15 از 17:
	 12
2 از 25:
	 12
4 از بیشتر از 30:
	 12
16 از 30:
	 12
6 از 3:
	 12
4 از 30:
	 12
7 از 17:
	 12
2 از 17:
	 12
5 از 19:
	 12
7 از 20:
	 12
22 از 25:
	 11
8 از 19:
	 11
7 از 21:
	 11
6 از 21:
	 11
11 از 17:
	 11
12 از 29:
	 11
2 از 19:
	 11
9 از 19:
	 11
10 از 21:
	 11
25 از 29:
	 11
13 از 25:
	 11
4 از 21:
	 11
1 از 17:
	 11
11 از 25:
	 11
12 از 22:
	 10
26:
	 10
28 از 29:
	 10
13 از 16:
	 10
20 از 30:
	 10
15 از 19:
	 10
21 از 21:
	 10
11 از 21:
	 10
10 از 19:
	 10
13 از 19:
	 10
همکف از 20:
	 9
16 از 19:
	 9
15 از 16:
	 9
20 از 21:
	 9
6 از بیشتر از 30:
	 9
2 از بیشتر از 30:
	 9
7 از 19:
	 9
1 از 21:
	 9
1 از 30:
	 8
13 از 21:
	 8
5 از 29:
	 8
15 از 29:
	 8
2 از 30:
	 8
6 از 22:
	 8
3 از 17:
	 8
25 از 30:
	 8
11 از 19:
	 8
18 از 21:
	 8
22 از 30:
	 8
11 از 16:
	 8
16 از 17:
	 8
17 از 18:
	 8
3 از 21:
	 8
زیرهمکف از 7:
	 8
2 از 22:
	 8
7 از بیشتر از 30:
	 8
3 از 30:
	 8
5 از بیشتر از 30:
	 8
4 از 29:
	 7
همکف از 13:
	 7
29:
	 7
20 از 29:
	 7
18 از 18:
	 7
7 از 4:
	 7
19 از 21:
	 7
1 از 29:
	 7
6 از 30:
	 7
24 از بیشتر از 30:
	 7
3 از 28:
	 7
24 از 30:
	 7
14 از 19:
	 7
5 از 21:
	 7
8 از 4:
	 7
26 از 29:
	 7
29 از 29:
	 7
27 از 29:
	 6
7 از 22:
	 6
6 از انتخاب نشده:
	 6
10 از 27:
	 6
8 از 5:
	 6
8 از بیشتر از 30:
	 6
9 از 21:
	 6
10 از 23:
	 6
5 از انتخاب نشده:
	 6
13 از 22:
	 6
19 از 29:
	 6
11 از بیشتر از 30:
	 6
13 از 30:
	 6
15 از 22:
	 6
+30 از 15:
	 6
زیرهمکف از 8:
	 6
21 از 22:
	 6
18 از 29:
	 6
22 از 24:
	 6
17 از 21:
	 6
همکف از بیشتر از 30:
	 5
13 از 29:
	 5
5 از 22:
	 5
همکف از 24:
	 5
23 از 27:
	 5
11 از 30:
	 5
+30 از 14:
	 5
8 از 30:
	 5
+30 از 16:
	 5
23 از 30:
	 5
13 از بیشتر از 30:
	 5
20 از 22:
	 5
7 از 24:
	 5
10 از 22:
	 5
28 از 30:
	 5
16 از 29:
	 5
24 از 27:
	 5
2 از 29:
	 5
10 از 29:
	 5
1 از 27:
	 4
20 از 24:
	 4
21 از 30:
	 4
24 از 28:
	 4
17 از 22:
	 4
3 از 22:
	 4
20 از بیشتر از 30:
	 4
15 از 27:
	 4
12 از 24:
	 4
22 از 26:
	 4
7 از 5:
	 4
9 از 30:
	 4
17 از بیشتر از 30:
	 4
1 از 22:
	 4
8 از 29:
	 4
2 از 21:
	 4
16 از 21:
	 4
+30 از 2:
	 4
7 از 2:
	 4
3 از 29:
	 4
18 از 22:
	 4
11 از 24:
	 4
2 از 28:
	 4
7 از 28:
	 4
14 از 21:
	 4
14 از بیشتر از 30:
	 4
23 از 26:
	 4
22 از 22:
	 4
16 از 27:
	 4
6 از 29:
	 4
16 از بیشتر از 30:
	 4
16 از 22:
	 4
17 از 30:
	 4
21 از 29:
	 3
24 از 26:
	 3
23 از بیشتر از 30:
	 3
8 از 26:
	 3
3 از 23:
	 3
15 از بیشتر از 30:
	 3
12 از 23:
	 3
4 از 27:
	 3
26 از 26:
	 3
12 از 30:
	 3
+30 از 20:
	 3
22 از 27:
	 3
9 از بیشتر از 30:
	 3
8 از 23:
	 3
26 از 27:
	 3
10 از بیشتر از 30:
	 3
13 از 4:
	 3
23 از 24:
	 3
14 از 22:
	 3
19 از 30:
	 3
19 از 24:
	 3
7 از 3:
	 3
13 از 24:
	 3
5 از 26:
	 3
+30 از 12:
	 3
8 از 7:
	 3
29 از 30:
	 3
30 از 30:
	 3
22 از 29:
	 3
9 از 22:
	 3
زیرهمکف از 9:
	 2
13 از 28:
	 2
15 از 26:
	 2
12 از بیشتر از 30:
	 2
9 از 29:
	 2
7 از انتخاب نشده:
	 2
14 از 29:
	 2
30 از 7:
	 2
+30 از 22:
	 2
26 از بیشتر از 30:
	 2
11 از 29:
	 2
4 از 28:
	 2
10 از 30:
	 2
22 از 23:
	 2
12 از 27:
	 2
28 از بیشتر از 30:
	 2
13 از 27:
	 2
9 از 2:
	 2
23 از 23:
	 2
+30 از 19:
	 2
6 از 23:
	 2
+30 از 21:
	 2
5 از 27:
	 2
18 از 27:
	 2
8 از 6:
	 2
21 از بیشتر از 30:
	 2
19 از 22:
	 2
21 از 27:
	 2
8 از 2:
	 2
همکف از 18:
	 2
30 از بیشتر از 30:
	 2
7 از 29:
	 2
18 از 30:
	 2
13 از 23:
	 2
17 از 29:
	 2
همکف از 22:
	 2
8 از 22:
	 2
9 از انتخاب نشده:
	 2
20 از 26:
	 2
+30 از 9:
	 2
+30 از 8:
	 2
12 از 4:
	 2
زیرهمکف از 15:
	 2
9 از 4:
	 2
10 از 8:
	 2
17 از 23:
	 2
2 از 26:
	 2
6 از 27:
	 2
14 از 12:
	 2
21 از 26:
	 2
10 از 6:
	 2
26 از 30:
	 2
14 از 27:
	 2
9 از 7:
	 2
25 از 28:
	 2
+30 از 17:
	 2
27 از 30:
	 2
19 از 26:
	 2
18 از بیشتر از 30:
	 2
25 از بیشتر از 30:
	 2
15 از 30:
	 2
همکف از 19:
	 2
14 از 30:
	 2
4 از 23:
	 2
5 از 28:
	 2
زیرهمکف از 11:
	 1
14 از 26:
	 1
14 از 4:
	 1
11 از 10:
	 1
27 از 27:
	 1
+30 از 13:
	 1
9 از 3:
	 1
12 از 11:
	 1
8 از 27:
	 1
19 از 6:
	 1
17 از 28:
	 1
25 از 26:
	 1
15 از 24:
	 1
زیرهمکف از 13:
	 1
8 از 3:
	 1
17 از 27:
	 1
24 از 16:
	 1
10 از 5:
	 1
11 از 2:
	 1
11 از 23:
	 1
26 از 28:
	 1
10 از 4:
	 1
4 از 26:
	 1
12 از 10:
	 1
19 از بیشتر از 30:
	 1
3 از 27:
	 1
11 از 3:
	 1
زیرهمکف از 12:
	 1
14 از 3:
	 1
16 از 24:
	 1
11 از 27:
	 1
20 از 27:
	 1
14 از 5:
	 1
3 از 26:
	 1
7 از 27:
	 1
21 از 23:
	 1
19 از 27:
	 1
6 از 26:
	 1
14 از 24:
	 1
15 از 28:
	 1
13 از 5:
	 1
11 از 5:
	 1
7 از 30:
	 1
12 از 2:
	 1
21 از 18:
	 1
22 از 10:
	 1
+30 از 18:
	 1
23 از 28:
	 1
همکف از 28:
	 1
6 از 28:
	 1
25 از 27:
	 1
30 از 8:
	 1
14 از 13:
	 1
9 از 23:
	 1
8 از 28:
	 1
24 از 29:
	 1
7 از 26:
	 1
17 از 6:
	 1
+30 از انتخاب نشده:
	 1
13 از 12:
	 1
15 از 2:
	 1
15 از 23:
	 1
20 از 6:
	 1
9 از 6:
	 1
18 از 23:
	 1
+30 از 5:
	 1
30 از 25:
	 1
9 از 24:
	 1
زیرهمکف از 14:
	 1
21 از 24:
	 1
22 از بیشتر از 30:
	 1
11 از انتخاب نشده:
	 1
+30 از 6:
	 1
8 از انتخاب نشده:
	 1
7 از 23:
	 1
17 از 24:
	 1
2 از 23:
	 1
30 از 2:
	 1
+30 از 30:
	 1
13 از 3:
	 1
29 از بیشتر از 30:
	 1
11 از 4:
	 1
15 از 6:
	 1

In [35]:
train_df['Rent_type'].value_counts()

Rent_type
غیر قابل تبدیل    377898
قابل تبدیل          3675
Name: count, dtype: int64

In [95]:
print(f"ratio of rooms more than 4 to total rooms:\n{len(train_df[train_df['Rooms'] == '+4'])/ len(train_df)*100:.2f}%")

ratio of rooms more than 4 to total rooms:
0.19%

In [90]:
import numpy as np
import pandas as pd

# --- Step 1: Standardize Missing Values ---
print("Replacing 'انتخاب نشده' and unknown with NaN...")
train_df.replace(['انتخاب نشده', 'unknown'], np.nan, inplace=True)
print("Replacement complete.")

# --- Step 2: Correct Data Types ---
# Convert the 'Year_built' column to a numeric type.
# The 'errors=coerce' argument will turn any values that cannot be converted into numbers into NaN.
# This is a safe way to handle potential data entry errors in the column.
print("\nConverting 'Year_built'/'Rooms' to numeric...")
train_df['Year_built'] = pd.to_numeric(train_df['Year_built'], errors='coerce')

room_mapping = {
    'بدون اتاق': 0,
    '+4': 4  # Applying the conservative approach
}

train_df['Rooms'] = train_df['Rooms'].replace(room_mapping)
train_df['Rooms'] = pd.to_datetime(train_df['Rooms'], errors='coerce')

print("Conversion complete.")


# --- Step 3: Verify the Changes ---
# Print the dataframe's info again to see the results of our cleaning.
print("\n" + "="*50)
print("Information about the DataFrame AFTER cleaning:")
print("="*50)
train_df.info()

Replacing 'انتخاب نشده' and unknown with NaN...
Replacement complete.

Converting 'Year_built'/'Rooms' to numeric...
Conversion complete.

==================================================
Information about the DataFrame AFTER cleaning:
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 478084 entries, 0 to 478083
Data columns (total 21 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Area                478056 non-null  float64
 1   Year_built          474344 non-null  float64
 2   Rooms               478056 non-null  float64
 3   Floor               478050 non-null  object
 4   Elevator            478050 non-null  float64
 5   Parking             478054 non-null  float64
 6   StorageRoom         478054 non-null  float64
 7   Rent_type           381573 non-null  object
 8   Units_per_floor     258944 non-null  object
 9   Building_direction  213311 non-null  object
 10  Unit_status         251803 non-null  object
 11  Floor_material      279081 non-null  object
 12  Bathroom            276441 non-null  object
 13  Balcony             275169 non-null  object
 14  Heating             254798 non-null  object
 15  Cooling             243915 non-null  object
 16  Hot_water_provider  259316 non-null  object
 17  District            278103 non-null  object
 18  Credit              478084 non-null  float64
 19  Rent                478084 non-null  float64
 20  city                478084 non-null  object
dtypes: float64(8), object(13)
memory usage: 76.6+ MB

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
ایجاد متغیر هدف
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در این قسمت باید متغیر هدف مسئله را ایجاد کنیم. در این مسئله هدف ما تخمین ارزش خانه‌های مورد نظر است. برای این منظور، با استفاده از فرمول زیر، ستونی با نام <code>Total</code> به مجموعه داده خود اضافه کنید تا مدل یادگیری ماشین خود را منطبق بر آن آموزش دهید.

$$ Total = Credit + (Rent * 33.33334)$$

</font>
</p>

In [ ]:
# TODO:

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
آموزش مدل
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    حال که داده را پاکسازی کرده و احتمالا ویژگی‌هایی را به آن افزوده یا از آن حذف کرده‌اید، وقت آن است که مدلی آموزش دهید که بتواند متغیر هدف این مسئله را پیش‌بینی کند. در این قسمت استفاده از هر نوع مدل مربوط به یادگیری ماشین کلاسیک مجاز می‌باشد.
    در این قسمت مدل مورد نظر باید طوری آموزش داده شود که قادر به پیش‌بینی مقادیر ستون <code>Total</code> باشد.
</font>
</p>

In [ ]:
# TODO:

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معیار ارزیابی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    معیاری که برای ارزیابی عملکرد مدل انتخاب کرده‌ایم، <code>r2_score</code> نام دارد.
    <br>
    این معیار، سنجه ارزیابی کیفیت مدل شماست. به عبارت بهتر در سامانه داوری هم از همین معیار برای نمره‌دهی استفاده شده است.
    <br>
    پیشنهاد می‌شود با توجه به این معیار، عملکرد مدل خود را بر روی مجموعه‌ی آموزش یا اعتبارسنجی ارزیابی کنید.
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font color="red"><b color='red'>توجه:</b></font>
<font face="vazir" size=3>
    برای دریافت نمره از این سوال لازم است تا دقت مدل شما از آستانه‌ی ۰.۴ بیشتر باشد.
    در صورتی که دقت مدل شما از ۰.۴ کمتر باشد نمره شما
    <b>صفر</b>
    خواهد شد و در غیر این صورت با فرمول زیر محاسبه می‌شود:
</font>
</p>

In [ ]:
from sklearn.metrics import r2_score

# TODO:

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
 پیش‌بینی برای داده تست و خروجی
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    پیش‌بینی مدل خود بر روی داده‌های آزمایش را در قالب یک <code>dataframe</code> در متغیری با نام <code>submission</code>ذخیره کنید.  این <code>dataframe</code> باید دارای یک ستون با نام <code>Total</code> باشد که ردیف <code>i</code>ام آن، پیش‌بینی شما برای سطر <code>i</code>ام مجموعه‌داده‌ی آزمون باشد.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|------|---|
|Total|قیمت واحد مسکونی (میلیون تومان)|
    
</font>
</div>
</center>

In [ ]:
# TODO:

submission = None